### ISSUE TITLE
Nice package, but why not copy the emoji into the source code?

### ISSUE THREAD

**Issue by martinrode** [enescakir/emoji#5]
Like this: 🥳

**Comment by enescakir** [comment]
Hi @martinrode,
If your font, IDE or OS don't support the specific emoji, you can't see it.
In addition, sometimes finding actual emoji strings is hard.
You have open emoji list on internet or emoji keyboard, and scroll crazily to find emoji.
But your IDE's auto-complete feature fills up missing parts for you.

`adiabatic` gives some reasons for usage on [reddit](https://www.reddit.com/r/golang/comments/fe21os/emoji_a_minimalistic_emoji_package_for_go/fjmbrnr).

I hope it makes sense.
